/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_evasalgado;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author evaja
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setLocation(400, 200);
        equipos.setVisible(false);
        estadios.setVisible(false);
        jugadores.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JTabbedPane();
        menuañadir = new javax.swing.JPanel();
        añadirequipo = new javax.swing.JButton();
        añadirestadio = new javax.swing.JButton();
        añadirjugador = new javax.swing.JButton();
        equipos = new javax.swing.JPanel();
        country = new javax.swing.JTextField();
        nameequipo = new javax.swing.JTextField();
        añadire = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        color = new javax.swing.JPanel();
        estadios = new javax.swing.JPanel();
        jugadores = new javax.swing.JPanel();
        menulistar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuañadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añadirequipo.setText("Añadir Equipo");
        añadirequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirequipoActionPerformed(evt);
            }
        });
        menuañadir.add(añadirequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 193, 85));

        añadirestadio.setText("Añadir Estadio");
        añadirestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirestadioActionPerformed(evt);
            }
        });
        menuañadir.add(añadirestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 193, 85));

        añadirjugador.setText("Añadir Jugador");
        añadirjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirjugadorActionPerformed(evt);
            }
        });
        menuañadir.add(añadirjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 193, 85));

        equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        country.setText("Ingrese el pais de origen");
        country.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryMouseClicked(evt);
            }
        });
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        equipos.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 146, 288, 42));

        nameequipo.setText("Ingrese el nombre del equipo");
        nameequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameequipoMouseClicked(evt);
            }
        });
        nameequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameequipoActionPerformed(evt);
            }
        });
        equipos.add(nameequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 89, 288, 42));

        añadire.setText("añadir");
        añadire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadireActionPerformed(evt);
            }
        });
        equipos.add(añadire, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 291, 113, 53));

        title.setBackground(new java.awt.Color(153, 51, 255));
        title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title.setText("AÑADIR EQUIPO");
        equipos.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, 288, 58));

        color.setBackground(new java.awt.Color(102, 0, 255));

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        equipos.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 280, 470));

        menuañadir.add(equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        javax.swing.GroupLayout estadiosLayout = new javax.swing.GroupLayout(estadios);
        estadios.setLayout(estadiosLayout);
        estadiosLayout.setHorizontalGroup(
            estadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        estadiosLayout.setVerticalGroup(
            estadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        menuañadir.add(estadios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        javax.swing.GroupLayout jugadoresLayout = new javax.swing.GroupLayout(jugadores);
        jugadores.setLayout(jugadoresLayout);
        jugadoresLayout.setHorizontalGroup(
            jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jugadoresLayout.setVerticalGroup(
            jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        menuañadir.add(jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        menu.addTab("Añadir", menuañadir);

        javax.swing.GroupLayout menulistarLayout = new javax.swing.GroupLayout(menulistar);
        menulistar.setLayout(menulistarLayout);
        menulistarLayout.setHorizontalGroup(
            menulistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        menulistarLayout.setVerticalGroup(
            menulistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        menu.addTab("Lista", menulistar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirjugadorActionPerformed
        // TODO add your handling code here:
        jugadores.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
    }//GEN-LAST:event_añadirjugadorActionPerformed

    private void añadirequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirequipoActionPerformed
        // TODO add your handling code here:

        equipos.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
    }//GEN-LAST:event_añadirequipoActionPerformed

    private void añadirestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirestadioActionPerformed
        // TODO add your handling code here:
        estadios.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
    }//GEN-LAST:event_añadirestadioActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_countryActionPerformed

    private void nameequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameequipoActionPerformed
        // TODO add your handling code here:                                    

    }//GEN-LAST:event_nameequipoActionPerformed

    private void nameequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameequipoMouseClicked
        if (nameequipo.getText().equals("Ingrese el nombre del equipo")) {
            nameequipo.setText("");
            nameequipo.setForeground(Color.GRAY);
        }
        if (country.getText().isEmpty()) {
            country.setText("Ingrese el pais de origen");
            country.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nameequipoMouseClicked

    private void countryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryMouseClicked
        if (country.getText().equals("Ingrese el pais de origen")) {
            country.setText("");
            country.setForeground(Color.GRAY);
        }
        if (nameequipo.getText().isEmpty()) {
            nameequipo.setText("Ingrese el nombre del equipo");
            nameequipo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_countryMouseClicked

    private void añadireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadireActionPerformed
        // TODO add your handling code here:
        Equipo = new equipo(nameequipo.getText(), country.getText());
        E.add(Equipo);
        JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
        equipos.setVisible(false);
        añadirequipo.setVisible(true);
        añadirestadio.setVisible(true);
        añadirjugador.setVisible(true);
    }//GEN-LAST:event_añadireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    equipo Equipo = new equipo();
    ArrayList<equipo> E = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadire;
    private javax.swing.JButton añadirequipo;
    private javax.swing.JButton añadirestadio;
    private javax.swing.JButton añadirjugador;
    private javax.swing.JPanel color;
    private javax.swing.JTextField country;
    private javax.swing.JPanel equipos;
    private javax.swing.JPanel estadios;
    private javax.swing.JPanel jugadores;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel menuañadir;
    private javax.swing.JPanel menulistar;
    private javax.swing.JTextField nameequipo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
