/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_evasalgado;

import java.awt.Color;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author evaja
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setLocation(400, 200);
        equipos.setVisible(false);
        estadios.setVisible(false);
        jugadores.setVisible(false);
        pie =  (DefaultComboBoxModel) pieh.getModel();
        pos = (DefaultComboBoxModel) Posicion.getModel();
        teams = (DefaultComboBoxModel) equipoestadio.getModel();
        pos.removeAllElements();
        teams.removeAllElements();
        pie.removeAllElements();
        for (int i = 0; i < E.size(); i++) {
            teams.addElement(E.get(i));
        }
        pos.addElement("portero");
        pos.addElement("Delantero");
        pos.addElement("Mediocampista");
        pos.addElement("Defensa");
        pie.addElement("Izquierda");
        pie.addElement("Derecha");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JTabbedPane();
        menuañadir = new javax.swing.JPanel();
        añadirequipo = new javax.swing.JButton();
        añadirestadio = new javax.swing.JButton();
        añadirjugador = new javax.swing.JButton();
        color1 = new javax.swing.JPanel();
        equipos = new javax.swing.JPanel();
        country = new javax.swing.JTextField();
        nameequipo = new javax.swing.JTextField();
        añadire = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        color = new javax.swing.JPanel();
        estadios = new javax.swing.JPanel();
        nameestadio = new javax.swing.JTextField();
        Ciudad = new javax.swing.JTextField();
        Capacidad = new javax.swing.JTextField();
        addestadio = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        equipoestadio = new javax.swing.JComboBox<>();
        jugadores = new javax.swing.JPanel();
        player = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        nacionalidad = new javax.swing.JTextField();
        pieh = new javax.swing.JComboBox<>();
        addjugador = new javax.swing.JButton();
        equipojuego = new javax.swing.JTextField();
        Posicion = new javax.swing.JComboBox<>();
        menulistar = new javax.swing.JPanel();
        eliminar = new javax.swing.JButton();
        eliminarlista = new javax.swing.JPanel();
        instruccion = new javax.swing.JLabel();
        aeliminar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        menu.setForeground(new java.awt.Color(0, 153, 255));

        menuañadir.setBackground(new java.awt.Color(0, 153, 255));
        menuañadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añadirequipo.setBackground(new java.awt.Color(255, 204, 51));
        añadirequipo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        añadirequipo.setForeground(new java.awt.Color(255, 255, 255));
        añadirequipo.setText("Añadir Equipo");
        añadirequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirequipoActionPerformed(evt);
            }
        });
        menuañadir.add(añadirequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 193, 85));

        añadirestadio.setBackground(new java.awt.Color(255, 204, 0));
        añadirestadio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        añadirestadio.setForeground(new java.awt.Color(255, 255, 255));
        añadirestadio.setText("Añadir Estadio");
        añadirestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirestadioActionPerformed(evt);
            }
        });
        menuañadir.add(añadirestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 193, 85));

        añadirjugador.setBackground(new java.awt.Color(255, 204, 0));
        añadirjugador.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        añadirjugador.setForeground(new java.awt.Color(255, 255, 255));
        añadirjugador.setText("Añadir Jugador");
        añadirjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirjugadorActionPerformed(evt);
            }
        });
        menuañadir.add(añadirjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 193, 85));

        color1.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout color1Layout = new javax.swing.GroupLayout(color1);
        color1.setLayout(color1Layout);
        color1Layout.setHorizontalGroup(
            color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        color1Layout.setVerticalGroup(
            color1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        menuañadir.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 360, 510));

        equipos.setBackground(new java.awt.Color(51, 153, 255));
        equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        country.setText("Ingrese el pais de origen");
        country.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryMouseClicked(evt);
            }
        });
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        equipos.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 146, 288, 42));

        nameequipo.setText("Ingrese el nombre del equipo");
        nameequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameequipoMouseClicked(evt);
            }
        });
        nameequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameequipoActionPerformed(evt);
            }
        });
        equipos.add(nameequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 89, 288, 42));

        añadire.setText("añadir");
        añadire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadireActionPerformed(evt);
            }
        });
        equipos.add(añadire, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 291, 113, 53));

        title.setBackground(new java.awt.Color(153, 51, 255));
        title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title.setText("AÑADIR EQUIPO");
        equipos.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, 288, 58));

        color.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        equipos.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 280, 470));

        menuañadir.add(equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        estadios.setBackground(new java.awt.Color(0, 153, 255));
        estadios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameestadio.setText("Ingrese nombre de estadio");
        nameestadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameestadioMouseClicked(evt);
            }
        });
        estadios.add(nameestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 70));

        Ciudad.setText("ingrese nombre de ciudad");
        Ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CiudadMouseClicked(evt);
            }
        });
        estadios.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 70));

        Capacidad.setText("capacidad: ");
        Capacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CapacidadMouseClicked(evt);
            }
        });
        estadios.add(Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 70));

        addestadio.setText("Añadir");
        addestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addestadioActionPerformed(evt);
            }
        });
        estadios.add(addestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 60));

        fondo.setBackground(new java.awt.Color(102, 0, 51));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        estadios.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 380, 500));

        equipoestadio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        equipoestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoestadioActionPerformed(evt);
            }
        });
        estadios.add(equipoestadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, -1));

        menuañadir.add(estadios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        jugadores.setBackground(new java.awt.Color(0, 153, 255));
        jugadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player.setBackground(new java.awt.Color(255, 204, 51));
        player.setForeground(new java.awt.Color(255, 255, 255));
        player.setText("Añadir Nombre de Jugador");
        player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerActionPerformed(evt);
            }
        });
        jugadores.add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 37, 180, 63));

        age.setBackground(new java.awt.Color(255, 204, 51));
        age.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Ingrese edad");
        jugadores.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 118, 180, 57));

        nacionalidad.setBackground(new java.awt.Color(255, 204, 51));
        nacionalidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        nacionalidad.setText("Nacionalidad");
        jugadores.add(nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 199, 180, 55));

        pieh.setBackground(new java.awt.Color(255, 204, 51));
        pieh.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        pieh.setForeground(new java.awt.Color(255, 255, 255));
        pieh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pieh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piehMouseClicked(evt);
            }
        });
        pieh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piehActionPerformed(evt);
            }
        });
        jugadores.add(pieh, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 272, -1, -1));

        addjugador.setBackground(new java.awt.Color(255, 204, 51));
        addjugador.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        addjugador.setForeground(new java.awt.Color(255, 255, 255));
        addjugador.setText("Añadir");
        addjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addjugadorMouseClicked(evt);
            }
        });
        jugadores.add(addjugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 331, 155, 76));

        equipojuego.setBackground(new java.awt.Color(255, 204, 51));
        equipojuego.setForeground(new java.awt.Color(255, 255, 255));
        equipojuego.setText("Equipo en el que está: ");
        equipojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipojuegoActionPerformed(evt);
            }
        });
        jugadores.add(equipojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 37, 180, 63));

        Posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosicionActionPerformed(evt);
            }
        });
        jugadores.add(Posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 110, 50));

        menuañadir.add(jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        menu.addTab("Añadir", menuañadir);

        menulistar.setBackground(new java.awt.Color(0, 153, 255));
        menulistar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setBackground(new java.awt.Color(255, 204, 0));
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menulistar.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 370, 220));

        eliminarlista.setBackground(new java.awt.Color(0, 153, 255));
        eliminarlista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instruccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        instruccion.setForeground(new java.awt.Color(102, 0, 0));
        instruccion.setText("Ingrese el nombre del equipo que desea eliminar: ");
        eliminarlista.add(instruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 521, 135));

        aeliminar.setBackground(new java.awt.Color(255, 204, 51));
        aeliminar.setForeground(new java.awt.Color(0, 0, 0));
        aeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeliminarActionPerformed(evt);
            }
        });
        eliminarlista.add(aeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 430, 145));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        eliminarlista.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, 90));

        menulistar.add(eliminarlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        menu.addTab("Lista", menulistar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         
    private void añadirjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirjugadorActionPerformed
        // TODO add your handling code here:
        jugadores.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
        
    }//GEN-LAST:event_añadirjugadorActionPerformed

    private void añadirequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirequipoActionPerformed
        // TODO add your handling code here:

        equipos.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
    }//GEN-LAST:event_añadirequipoActionPerformed

    private void añadirestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirestadioActionPerformed
        // TODO add your handling code here:

        estadios.setVisible(true);
        añadirequipo.setVisible(false);
        añadirestadio.setVisible(false);
        añadirjugador.setVisible(false);
    }//GEN-LAST:event_añadirestadioActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_countryActionPerformed

    private void nameequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameequipoActionPerformed
        // TODO add your handling code here:                                    

    }//GEN-LAST:event_nameequipoActionPerformed

    private void nameequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameequipoMouseClicked
        if (nameequipo.getText().equals("Ingrese el nombre del equipo")) {
            nameequipo.setText("");
            nameequipo.setForeground(Color.GRAY);
        }
        if (country.getText().isEmpty()) {
            country.setText("Ingrese el pais de origen");
            country.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nameequipoMouseClicked

    private void countryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryMouseClicked
        if (country.getText().equals("Ingrese el pais de origen")) {
            country.setText("");
            country.setForeground(Color.GRAY);
        }
        if (nameequipo.getText().isEmpty()) {
            nameequipo.setText("Ingrese el nombre del equipo");
            nameequipo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_countryMouseClicked

    private void añadireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadireActionPerformed
        // TODO add your handling code here:
        Equipo = new equipo(nameequipo.getText(), country.getText());
        E.add(Equipo);
        JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
        equipos.setVisible(false);
        añadirequipo.setVisible(true);
        añadirestadio.setVisible(true);
        añadirjugador.setVisible(true);
    }//GEN-LAST:event_añadireActionPerformed

    private void addestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addestadioActionPerformed
        // TODO add your handling code here:
        Estadios.add(new estadio(nameestadio.getText(), Ciudad.getText(), Integer.parseInt(Capacidad.getText())));
        JOptionPane.showMessageDialog(this, "Estadio agregado exitosamente");
        estadios.setVisible(false);
        añadirequipo.setVisible(true);
        añadirestadio.setVisible(true);
        añadirjugador.setVisible(true);
    }//GEN-LAST:event_addestadioActionPerformed

    private void nameestadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameestadioMouseClicked
        if (nameestadio.getText().equals("Ingrese nombre de estadio")) {
            nameestadio.setText("");
            nameestadio.setForeground(Color.BLACK);
        }
        if (Ciudad.getText().isEmpty()) {
            Ciudad.setText("ingrese nombre de ciudad");
            Ciudad.setForeground(Color.gray);
        }
         if (Capacidad.getText().isEmpty()) {
            Capacidad.setText("capacidad:");
            Capacidad.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_nameestadioMouseClicked

    private void CiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CiudadMouseClicked
        // TODO add your handling code here:
       
        if (Ciudad.getText().equals("ingrese nombre de ciudad")) {
            Ciudad.setText("");
            Ciudad.setForeground(Color.BLACK);
        }
          if (nameestadio.getText().isEmpty()) {
            nameestadio.setText("Ingrese nombre de estadio");
            nameestadio.setForeground(Color.gray);
        }
         if (Capacidad.getText().isEmpty()) {
            Capacidad.setText("capacidad:");
            Capacidad.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CiudadMouseClicked

    private void CapacidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CapacidadMouseClicked
         if (Capacidad.getText().equals("capacidad:")) {
            Capacidad.setText("");
            Capacidad.setForeground(Color.BLACK);
        }
        if (Ciudad.getText().isEmpty()) {
            Ciudad.setText("ingrese nombre de ciudad");
            Ciudad.setForeground(Color.gray);
        }
          if (nameestadio.getText().isEmpty()) {
            nameestadio.setText("Ingrese nombre de estadio");
            nameestadio.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_CapacidadMouseClicked

    private void playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerActionPerformed

    private void piehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piehActionPerformed
        
        
    }//GEN-LAST:event_piehActionPerformed

    private void piehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piehMouseClicked
        pieh.setModel(pie);
    }//GEN-LAST:event_piehMouseClicked

    private void equipoestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoestadioActionPerformed

        equipoestadio.setModel(teams);
        
    }//GEN-LAST:event_equipoestadioActionPerformed

    private void addjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addjugadorMouseClicked
  
        
    }//GEN-LAST:event_addjugadorMouseClicked

    private void equipojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipojuegoActionPerformed
        for (int i = 0; i < E.size(); i++) {
            if(equipojuego.getText().equals(E.get(i).getNombre())){
            }
        }
    }//GEN-LAST:event_equipojuegoActionPerformed

    private void PosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosicionActionPerformed
        Posicion.setModel(pos);
    }//GEN-LAST:event_PosicionActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void aeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aeliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < E.size(); i++) {
            if (aeliminar.equals(E.get(i).getNombre())) {
               E.remove(i);
            }
        }
        JOptionPane.showMessageDialog(this, "Contenido removido");
        eliminarlista.setVisible(false);
        menulistar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    ArrayList<jugador> j = new ArrayList<>();
    ArrayList todos = new ArrayList();
    DefaultComboBoxModel pos = new DefaultComboBoxModel();
    DefaultComboBoxModel teams = new DefaultComboBoxModel();
    DefaultComboBoxModel pie = new DefaultComboBoxModel();
    equipo Equipo = new equipo();
    ArrayList<equipo> E = new ArrayList<>();
    ArrayList<estadio> Estadios = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Capacidad;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JComboBox<String> Posicion;
    private javax.swing.JButton addestadio;
    private javax.swing.JButton addjugador;
    private javax.swing.JTextField aeliminar;
    private javax.swing.JTextField age;
    private javax.swing.JButton añadire;
    private javax.swing.JButton añadirequipo;
    private javax.swing.JButton añadirestadio;
    private javax.swing.JButton añadirjugador;
    private javax.swing.JPanel color;
    private javax.swing.JPanel color1;
    private javax.swing.JTextField country;
    private javax.swing.JButton eliminar;
    private javax.swing.JPanel eliminarlista;
    private javax.swing.JComboBox<String> equipoestadio;
    private javax.swing.JTextField equipojuego;
    private javax.swing.JPanel equipos;
    private javax.swing.JPanel estadios;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel instruccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jugadores;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel menuañadir;
    private javax.swing.JPanel menulistar;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nameequipo;
    private javax.swing.JTextField nameestadio;
    private javax.swing.JComboBox<String> pieh;
    private javax.swing.JTextField player;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
